<_type = typeOf _towing;
switch (_type) do
	{
		case "Jonzie_Datsun_Z432": {_height = _height + 0.4;_distance = _distance -5.5;};		
		case "Jonzie_Ceed": {_height = _height + 0.54;_distance = _distance -5.5;};		
		case "Jonzie_Datsun_510": {_height = _height -1.05;_distance = _distance -5.5;};		
		case "Jonzie_Corolla": {_height = _height - 0.13;_distance = _distance -5.5;};		
		case "Jonzie_Volvo_242": {_height = _height -1.09;_distance = _distance -5.5;};
		case "Jonzie_Highway": {_height = _height -1.09;_distance = _distance -5.5;};
		case "Jonzie_VE": {_height = _height -1.09;_distance = _distance -5.5;};				
		case "Jonzie_30CSL": {_height = _height + 0.4;_distance = _distance -5.5;};		
		case "Jonzie_STI": {_height = _height -1.08;_distance = _distance -5.5;};
		case "Jonzie_Galant": {_height = _height + 0.45;_distance = _distance -5.5;};
		case "Jonzie_Mini_Cooper": {_height = _height + 0.45;_distance = _distance -5.5;};
		case "Jonzie_Mini_Cooper_R_spec": {_height = _height + 0.45;_distance = _distance -5.5;};
		case "Jonzie_Ute": {_height = _height -1;_distance = _distance -5.5;};
		case "Jonzie_Car_Crash": {_height = _height + -1.1;_distance = _distance -5.5;};
		case "Jonzie_Ambulance": {_height = _height -1.2;_distance = _distance -5.5;};
		case "Jonzie_Forklift": {_height = _height -0.9;_distance = _distance -4;};	
		case "Jonzie_Viper": {_height = _height - 1.0;_distance = _distance -5.5;};
		case "Jonzie_Escalade": {_height = _height -0.8;_distance = _distance -5.5;};
		case "Jonzie_Raptor": {_height = _height -0.59;_distance = _distance -5.5;};
		case "Jonzie_Transit": {_height = _height -0.76;_distance = _distance -5.5;};
		case "Jonzie_Quattroporte": {_height = _height + 0.43;_distance = _distance -5.5;};
		case "C_Hatchback_01_F": {_height = _height + 0.25;_distance = _distance -5.5;};
		case "C_Hatchback_01_sport_F": {_height = _height + 0.25;_distance = _distance -5.5;};
		case "B_MRAP_01_F": {_height = _height + 0.6;_distance = _distance -5.5;_Edistance = _Edistance + 1;};
		case "B_MRAP_01_gmg_F": {_height = _height + 0.6;_distance = _distance -5.5;_Edistance = _Edistance + 1;};
		case "B_MRAP_01_hmg_F": {_height = _height + 0.6;_distance = _distance -5.5;_Edistance = _Edistance + 1;};
		case "O_MRAP_02_F": {_height = _height + 0.9;_distance = _distance -5.5;_Edistance = _Edistance + 1;};
		case "O_MRAP_02_gmg_F": {_height = _height + 0.9;_distance = _distance -5.5;_Edistance = _Edistance + 1;};
		case "O_MRAP_02_hmg_F": {_height = _height + 0.9;_distance = _distance -5.5;_Edistance = _Edistance + 1;};
		case "C_Kart_01_F": {_height = _height -0.05;_distance = _distance -5.5;};
		case "C_Kart_01_Blu_F": {_height = _height -0.05;_distance = _distance -5.5;};	
		case "C_Kart_01_Fuel_F": {_height = _height -0.05;_distance = _distance -5.5;};	
		case "C_Kart_01_Red_F": {_height = _height -0.05;_distance = _distance -5.5;};	
		case "C_Kart_01_Vrana_F": {_height = _height -0.05;_distance = _distance -5.5;};	
		case "C_Offroad_01_F": {_height = _height + 0.45;_distance = _distance -5.5;};	
		case "B_G_Offroad_01_F": {_height = _height + 0.45;_distance = _distance -5.5;};	
		case "I_Quadbike_01_F": {_height = _height + 0.3;_distance = _distance -5.5;};	
		case "C_Quadbike_01_F": {_height = _height + 0.3;_distance = _distance -5.5;};		
		case "O_Quadbike_01_F": {_height = _height + 0.3;_distance = _distance -5.5;};		
		case "B_G_Quadbike_01_F": {_height = _height + 0.3;_distance = _distance -5.5;};		
		case "B_Quadbike_01_F": {_height = _height + 0.3;_distance = _distance -5.5;};
		case "I_MRAP_03_F": {_height = _height + 0.55;_distance = _distance -5.5;};
		case "I_MRAP_03_gmg_F": {_height = _height + 0.55;_distance = _distance -5.5;};
		case "I_MRAP_03_hmg_F": {_height = _height + 0.55;_distance = _distance -5.5;};
	        case "tw_raptor_marked": {_height = _height + 0.59;_distance = _distance -5.5;};
		case "C_SUV_01_F": {_height = _height + 0.35;_distance = _distance -5.5;};
		case "tw_explorer_marked": {_height = _height -0.35;_distance = _distance -5.5;};
		case "C_Van_01_transport_F": {_height = _height + 0.6;_distance = _distance -5.5;};	
		case "B_G_Van_01_transport_F": {_height = _height + 0.6;_distance = _distance -5.5;};	
		case "C_Van_01_box_F": {_height = _height + 0.6;_distance = _distance -5.5;};																					
	};	
