switch (_type) do
	{
		case "Jonzie_Datsun_Z432": {_height = _height + 1.5;_distance = _distance - 0;_Edistance = _distance - 5.5;_Eheight = _height - 1;};		
		case "Jonzie_Ceed": {_height = _height + 1.64;_distance = _distance - 0;_Edistance = _distance - 5.4;_Eheight = _height - 1;};		
		case "Jonzie_Datsun_510": {_height = _height + 0;_distance = _distance - 0;_Edistance = _distance - 5.5;_Eheight = _height - 1;};	
		case "Jonzie_Corolla": {_height = _height + 0.97;_distance = _distance - 0;_Edistance = _distance - 5.4;_Eheight = _height - 1;};		
		case "Jonzie_30CSL": {_height = _height + 1.5;_distance = _distance - 0;_Edistance = _distance - 5.5;_Eheight = _height - 1;};		
		case "Jonzie_Highway": {_height = _height + 0.1;_distance = _distance - 0;_Edistance = _distance - 5.8;_Eheight = _height - 1.5;};
		case "Jonzie_VE": {_height = _height + 0.1;_distance = _distance - 0;_Edistance = _distance - 5.8;_Eheight = _height - 1.5;};			
		case "Jonzie_Galant": {_height = _height + 1.55;_distance = _distance - 0;_Edistance = _distance - 4.8;_Eheight = _height - 1;};	
		case "Jonzie_Mini_Cooper": {_height = _height + 1.5;_distance = _distance - 0;_Edistance = _distance - 3.5;_Eheight = _height - 1;};	
		case "Jonzie_Mini_Cooper_R_spec": {_height = _height + 1.5;_distance = _distance - 0;_Edistance = _distance - 3.5;_Eheight = _height - 1;};	
		case "Jonzie_Ute": {_height = _height + 0.1;_distance = _distance - 0;_Edistance = _distance - 5.8;_Eheight = _height - 1.5;};
		case "Jonzie_Ambulance": {_height = _height - 0.2;_distance = _distance - 0.2;_Edistance = _distance -6.2;_Eheight = _height - 0.8;};
		case "Jonzie_Forklift": {_height = _height - 0.25;_distance = _distance - 0.15;_Edistance = _distance -5.0;_Eheight = _height - 1.3;};
		case "Jonzie_Viper": {_height = _height + 0.1;_distance = _distance - 0;_Edistance = _distance - 5.5;_Eheight = _height - 1.5;};
		case "Jonzie_Escalade": {_height = _height + 0.3;_distance = _distance - 0;_Edistance = _distance - 6.5;_Eheight = _height - 1.5;};
		case "Jonzie_Raptor": {_height = _height + 0.51;_distance = _distance - 0;_Edistance = _distance - 6.0;_Eheight = _height - 1.5;};
		case "Jonzie_Transit": {_height = _height + 0.34;_distance = _distance - 0;_Edistance = _distance - 6.0;_Eheight = _height - 1.5;};
		case "Jonzie_Quattroporte": {_height = _height + 1.53;_distance = _distance - 0;_Edistance = _distance - 6.0;_Eheight = _height - 1.5;};
		case "C_Hatchback_01_F": {_height = _height + 1.35;_distance = _distance - 0;_Edistance = _distance - 6.0;_Eheight = _height - 1.5;};
		case "C_Hatchback_01_sport_F": {_height = _height + 1.35;_distance = _distance - 0;_Edistance = _distance - 6.0;_Eheight = _height - 1.5;};
		case "B_MRAP_01_F": {_height = _height + 2;_distance = _distance - 0;_Edistance = _distance - 5.0;_Eheight = _height - 1.5;};
		case "B_MRAP_01_gmg_F": {_height = _height + 2;_distance = _distance - 0;_Edistance = _distance - 5.0;_Eheight = _height - 1.5;};
		case "B_MRAP_01_hmg_F": {_height = _height + 2;_distance = _distance - 0;_Edistance = _distance - 5.0;_Eheight = _height - 1.5;};
		case "O_MRAP_02_F": {_height = _height + 2.3;_distance = _distance - 0;_Edistance = _distance - 5.0;_Eheight = _height - 1.5;};
		case "O_MRAP_02_gmg_F": {_height = _height + 2.3;_distance = _distance - 0;_Edistance = _distance - 5.0;_Eheight = _height - 1.5;};
		case "O_MRAP_02_hmg_F": {_height = _height + 2.3;_distance = _distance - 0;_Edistance = _distance - 5.0;_Eheight = _height - 1.5;};
		case "C_Kart_01_F": {_height = _height + 1.05;_distance = _distance - 0;_Edistance = _distance - 5.0;_Eheight = _height - 1.5;};
		case "C_Kart_01_Blu_F": {_height = _height + 1.05;_distance = _distance - 0;_Edistance = _distance - 5.0;_Eheight = _height - 1.5;};
		case "C_Kart_01_Fuel_F": {_height = _height + 1.05;_distance = _distance - 0;_Edistance = _distance - 5.0;_Eheight = _height - 1.5;};
		case "C_Kart_01_Red_F": {_height = _height + 1.05;_distance = _distance - 0;_Edistance = _distance - 5.0;_Eheight = _height - 1.5;};
		case "C_Kart_01_Vrana_F": {_height = _height + 1.05;_distance = _distance - 0;_Edistance = _distance - 5.0;_Eheight = _height - 1.5;};
		case "C_Offroad_01_F": {_height = _height + 1.55;_distance = _distance - 0;_Edistance = _distance - 6.0;_Eheight = _height - 1.5;};
		case "B_G_Offroad_01_F": {_height = _height + 1.55;_distance = _distance - 0;_Edistance = _distance - 6.0;_Eheight = _height - 1.5;};
		case "I_Quadbike_01_F": {_height = _height + 1.4;_distance = _distance - 0;_Edistance = _distance - 4.5;_Eheight = _height - 1.5;};
		case "C_Quadbike_01_F": {_height = _height + 1.4;_distance = _distance - 0;_Edistance = _distance - 4.5;_Eheight = _height - 1.5;};
		case "O_Quadbike_01_F": {_height = _height + 1.4;_distance = _distance - 0;_Edistance = _distance - 4.5;_Eheight = _height - 1.5;};
		case "B_G_Quadbike_01_F": {_height = _height + 1.4;_distance = _distance - 0;_Edistance = _distance - 4.5;_Eheight = _height - 1.5;};
		case "B_Quadbike_01_F": {_height = _height + 1.4;_distance = _distance - 0;_Edistance = _distance - 4.5;_Eheight = _height - 1.5;};
		case "I_MRAP_03_F": {_height = _height + 1.65;_distance = _distance - 0;_Edistance = _distance - 6.0;_Eheight = _height - 1.5;};
		case "I_MRAP_03_gmg_F": {_height = _height + 1.65;_distance = _distance - 0;_Edistance = _distance - 6.0;_Eheight = _height - 1.5;};
		case "I_MRAP_03_hmg_F": {_height = _height + 1.65;_distance = _distance - 0;_Edistance = _distance - 6.0;_Eheight = _height - 1.5;};
		case "C_SUV_01_F": {_height = _height + 1.45;_distance = _distance - 0;_Edistance = _distance - 6.0;_Eheight = _height - 1.5;};
		case "C_Van_01_transport_F": {_height = _height + 1.7;_distance = _distance - 0;_Edistance = _distance - 5.5;_Eheight = _height - 1.5;};
		case "B_G_Van_01_transport_F": {_height = _height + 1.7;_distance = _distance - 0;_Edistance = _distance - 5.5;_Eheight = _height - 1.5;};
		case "C_Van_01_box_F": {_height = _height + 1.7;_distance = _distance - 0;_Edistance = _distance - 5.5;_Eheight = _height - 1.5;};
	};
